### ISSUE TITLE
Phone numbers

### ISSUE THREAD

**Issue by Imagine3D-Ben** [RinsibleElk/Deadfile#21] opened 2016-12-13 14:56 UTC
If you edit a client and accidentally add a letter to the phone number field even if you empty that field it never lets you save it

**Comment by RinsibleElk** [comment] 2016-12-13 20:09
The issue is not with the original letter added - this is something I thought I'd fixed before where it really distinguishes between null (valid - this just means the optional field is not supplied) and "" (this is considered a value and is validated as not being a phone number). I've fixed this in other places by just recognising "" and interpreting as null manually.

**Comment by RinsibleElk** [comment] 2016-12-13 20:11
Turns out I'd fixed it for phone numbers 2 and 3 but not 1 because 1 was previously mandatory - until I found out how few of your clients you have phone numbers input for atm! Fixed now.

**Closed by RinsibleElk** 2016-12-13 20:11 UTC
Labels: bug
